name: norminette

on:
  push:
    branches:
      - '*'

jobs:
  pre-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install norminette
      run: |
        pip install norminette

    - name: Run norminette
      run: |
        python -m norminette libft main.c #srcs
